# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mike/workplace/graph/basis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mike/workplace/graph/basis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mike/workplace/graph/basis/CMakeFiles /home/mike/workplace/graph/basis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mike/workplace/graph/basis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bfs

# Build rule for target.
bfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bfs
.PHONY : bfs

# fast build rule for target.
bfs/fast:
	$(MAKE) -f CMakeFiles/bfs.dir/build.make CMakeFiles/bfs.dir/build
.PHONY : bfs/fast

#=============================================================================
# Target rules for targets named tt

# Build rule for target.
tt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tt
.PHONY : tt

# fast build rule for target.
tt/fast:
	$(MAKE) -f CMakeFiles/tt.dir/build.make CMakeFiles/tt.dir/build
.PHONY : tt/fast

#=============================================================================
# Target rules for targets named dfs

# Build rule for target.
dfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dfs
.PHONY : dfs

# fast build rule for target.
dfs/fast:
	$(MAKE) -f CMakeFiles/dfs.dir/build.make CMakeFiles/dfs.dir/build
.PHONY : dfs/fast

BFS.o: BFS.cpp.o

.PHONY : BFS.o

# target to build an object file
BFS.cpp.o:
	$(MAKE) -f CMakeFiles/bfs.dir/build.make CMakeFiles/bfs.dir/BFS.cpp.o
.PHONY : BFS.cpp.o

BFS.i: BFS.cpp.i

.PHONY : BFS.i

# target to preprocess a source file
BFS.cpp.i:
	$(MAKE) -f CMakeFiles/bfs.dir/build.make CMakeFiles/bfs.dir/BFS.cpp.i
.PHONY : BFS.cpp.i

BFS.s: BFS.cpp.s

.PHONY : BFS.s

# target to generate assembly for a file
BFS.cpp.s:
	$(MAKE) -f CMakeFiles/bfs.dir/build.make CMakeFiles/bfs.dir/BFS.cpp.s
.PHONY : BFS.cpp.s

DFS.o: DFS.cpp.o

.PHONY : DFS.o

# target to build an object file
DFS.cpp.o:
	$(MAKE) -f CMakeFiles/dfs.dir/build.make CMakeFiles/dfs.dir/DFS.cpp.o
.PHONY : DFS.cpp.o

DFS.i: DFS.cpp.i

.PHONY : DFS.i

# target to preprocess a source file
DFS.cpp.i:
	$(MAKE) -f CMakeFiles/dfs.dir/build.make CMakeFiles/dfs.dir/DFS.cpp.i
.PHONY : DFS.cpp.i

DFS.s: DFS.cpp.s

.PHONY : DFS.s

# target to generate assembly for a file
DFS.cpp.s:
	$(MAKE) -f CMakeFiles/dfs.dir/build.make CMakeFiles/dfs.dir/DFS.cpp.s
.PHONY : DFS.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/tt.dir/build.make CMakeFiles/tt.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/tt.dir/build.make CMakeFiles/tt.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/tt.dir/build.make CMakeFiles/tt.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... bfs"
	@echo "... tt"
	@echo "... dfs"
	@echo "... rebuild_cache"
	@echo "... BFS.o"
	@echo "... BFS.i"
	@echo "... BFS.s"
	@echo "... DFS.o"
	@echo "... DFS.i"
	@echo "... DFS.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

